before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: zxZs0IRL4PpLRe2LkJujwqX4DRKVTQp6vcqADqSi9h0kGOtD8Yel3lixxjpWpi8Z66KVf/8dwdg/m/REstuXuoz3qHO+HORXzA3IMTXPH3bmYVbIvEzAmxpNXpsBEF1YUFhRzzBxO6Aoean+/4JrvgQPf/srLJWyObIlsCRbDElwMfJ5cV4SHmlk8mEUFXCcn36rCOBRQhfd1HlpclQ2UxenZ/fJTuONtmi82h7DDHXi5F+SEouPU8IZEppT85l/pcfYZn1VyIyqElnt5a/SiznO1G0C18mAgLljZy0iG66jWdwMe/XJ+u/zkeAMZsfFOXlnQgjVafpmGVUplVAsQ8SUwcXLYhal5nvD57rGXPGOWDlEktdDOaClHogkdk9viAWZzPxmxgwtzphiU4MFsIcvcVJLTHy7REiugd2HARvficYzFcAStlP8peEzBlE69+eB87DrNM9yZ5U59gFOSPdwGOfnclsKZ0CQe7KEF7ZD66fmyNz/4BkN8gEFBkJKxYTGqoSTXiEcnrSc/htxyjE9q7q0TY5sGIBSzk7244+FxkoijnBUlbaug6UOe++a21Mymr901v5fUc3Rgw4Tjnyg+q58Ndl1wba7goYzx62uMOjFBTjRrdi12+nyhn5mrz4doPmKVdD0xcgZl0eGf8KGgcgbHupwpHthDkyCy/E= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
